function ekf = create_ekf_fused_urban(env, cfg, initial_position)
state0 = [initial_position; 0; 0; 0];
ekf = extendedKalmanFilter( ...
    @(x) stateFcn(cfg, x), ...
    @(x, ref_idx) measFcn_fused(x, env.tx, cfg, env, ref_idx), ...
    state0);
ekf.ProcessNoise = diag([5, 5, 0.5, 1, 1, 0.1]);
end